spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: ALWAYS
    url: jdbc:mysql://localhost:3306/order-management
    username: USER_NAME
    password: PASSWORD
  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: '8080'
  ##servlet:
  ##  contextPath: /api
logging:
  level:
    org:
      hibernate:
        SQL: debug